services:
  db:
    image: postgres:16
    container_name: warranty-claim-tracker-db
    environment:
      POSTGRES_USER: adminuser
      POSTGRES_PASSWORD: Password
      POSTGRES_DB: warranty_claim_tracker
    ports:
      - "51214:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: