// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });

// import { defineConfig } from "prisma/config";
// import { PrismaPg } from "@prisma/adapter-pg";
// import * as fs from "fs";
// import * as path from "path";

// // Manually load .env since Prisma doesn't inject it into the adapter env param
// function loadEnv() {
//   const envPath = path.resolve(process.cwd(), ".env");
//   if (!fs.existsSync(envPath)) return;
//   const lines = fs.readFileSync(envPath, "utf-8").split("\n");
//   for (const line of lines) {
//     const trimmed = line.trim();
//     if (!trimmed || trimmed.startsWith("#")) continue;
//     const [key, ...rest] = trimmed.split("=");
//     const value = rest.join("=").replace(/^["']|["']$/g, "");
//     if (key && !process.env[key]) {
//       process.env[key] = value;
//     }
//   }
// }

// loadEnv();

// export default defineConfig({
//   earlyAccess: true,
//   schema: "prisma/schema.prisma",
//   migrate: {
//     async adapter(env) {
//       return new PrismaPg({ connectionString: env.DATABASE_URL });
//     },
//   },
// });

// import { defineConfig } from "prisma/config";
// import * as dotenv from "dotenv";
// import * as path from "path";

// dotenv.config({ path: path.resolve(process.cwd(), ".env") });

// export default defineConfig({
//   earlyAccess: true,
//   schema: "prisma/schema.prisma",
//   migrate: {
//     url: process.env.DATABASE_URL!,
//   },
// });

import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  earlyAccess: true,
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});