apiVersion: v1
kind: Service
metadata:
  name: warranty-claim-tracker
  namespace: warranty-claim-tracker
  labels:
    app: warranty-claim-tracker
spec:
  type: ClusterIP
  selector:
    app: warranty-claim-tracker
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
